<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="generator" content="Hugo 0.73.0" />


<title>Heart attack risk analysis - Roy Blogdown</title>
<meta property="og:title" content="Heart attack risk analysis - Roy Blogdown">


  <link href='/featured.ico' rel='icon' type='image/x-icon'/>



  








<link href='//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css' rel='stylesheet' type='text/css' />



<link rel="stylesheet" href="/css/fonts.css" media="all">
<link rel="stylesheet" href="/css/main.css" media="all">



  </head>
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav">
  <a href="/" class="nav-logo">
    <img src="/images/featured.png"
         width="50"
         height="50"
         alt="Roy Blogdown">
  </a>

  <ul class="nav-links">
    
    <li><a href="/about/">About</a></li>
    
    <li><a href="https://www.linkedin.com/in/roy-w-a5bb3b83/">LinkedIn</a></li>
    
    <li><a href="/res/">Resources</a></li>
    
  </ul>
</nav>

      </header>


<main class="content" role="main">

  <article class="article">
    
    <span class="article-duration">15 min read</span>
    

    <h1 class="article-title">Heart attack risk analysis</h1>

    
    <span class="article-date">2021-05-10</span>
    

    <div class="article-content">
      
<script src="/2021/05/10/heart-attack-risk-analysis/index_files/header-attrs/header-attrs.js"></script>


<pre class="r"><code>library(tidyverse)
library(readr)
library(broom)
theme_set(theme_minimal())

heart &lt;- read_csv(&quot;heart.csv&quot;)</code></pre>
<p>The dataset can be found on <a href="https://www.kaggle.com/rashikrahmanpritom/heart-attack-analysis-prediction-dataset">kaggle</a></p>
<pre class="r"><code>glimpse(heart)</code></pre>
<pre><code>## Rows: 303
## Columns: 14
## $ age      &lt;dbl&gt; 63, 37, 41, 56, 57, 57, 56, 44, 52, 57, 54, 48, 49, 64, 58, 5~
## $ sex      &lt;dbl&gt; 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1~
## $ cp       &lt;dbl&gt; 3, 2, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 1, 3, 3, 2, 2, 3, 0, 3, 0~
## $ trtbps   &lt;dbl&gt; 145, 130, 130, 120, 120, 140, 140, 120, 172, 150, 140, 130, 1~
## $ chol     &lt;dbl&gt; 233, 250, 204, 236, 354, 192, 294, 263, 199, 168, 239, 275, 2~
## $ fbs      &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0~
## $ restecg  &lt;dbl&gt; 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1~
## $ thalachh &lt;dbl&gt; 150, 187, 172, 178, 163, 148, 153, 173, 162, 174, 160, 139, 1~
## $ exng     &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0~
## $ oldpeak  &lt;dbl&gt; 2.3, 3.5, 1.4, 0.8, 0.6, 0.4, 1.3, 0.0, 0.5, 1.6, 1.2, 0.2, 0~
## $ slp      &lt;dbl&gt; 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 0, 2, 2, 1~
## $ caa      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0~
## $ thall    &lt;dbl&gt; 1, 2, 2, 2, 2, 1, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3~
## $ output   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~</code></pre>
<p>N = 303</p>
<div id="explanation-of-features" class="section level1">
<h1>Explanation of features</h1>
<ol style="list-style-type: decimal">
<li>age - age in years</li>
<li>sex - sex (1 = male; 0 = female)</li>
<li>cp - chest pain type (1 = typical angina; 2 = atypical angina; 3 = non-anginal pain; 0 = asymptomatic)</li>
<li>trestbps - resting blood pressure (in mm Hg on admission to the hospital)</li>
<li>chol - serum cholestoral in mg/dl</li>
<li>fbs - fasting blood sugar &gt; 120 mg/dl (1 = true; 0 = false)</li>
<li>restecg - resting electrocardiographic results (1 = normal; 2 = having ST-T wave abnormality; 0 = hypertrophy)</li>
<li>thalach - maximum heart rate achieved</li>
<li>exang - exercise induced angina (1 = yes; 0 = no)</li>
<li>oldpeak - ST depression induced by exercise relative to rest</li>
<li>slope - the slope of the peak exercise ST segment (2 = upsloping; 1 = flat; 0 = downsloping)</li>
<li>ca - number of major vessels (0-3) colored by flourosopy</li>
<li>thal - 2 = normal; 1 = fixed defect; 3 = reversable defect</li>
<li>output - diagnosis of heart disease</li>
</ol>
<p>It is my understanding that the ST is a specific interval of time during an electrocardiogram stress test.</p>
</div>
<div id="exploring-the-dataset" class="section level1">
<h1>Exploring the dataset</h1>
<pre class="r"><code>heart %&gt;% 
  count(output)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   output     n
## *  &lt;dbl&gt; &lt;int&gt;
## 1      0   138
## 2      1   165</code></pre>
<p>The dataset represents 54.46% of people who suffer with heart disease.</p>
<div id="covariance-matrix" class="section level2">
<h2>Covariance matrix</h2>
<pre class="r"><code>g &lt;- cor(heart)

corrplot::corrplot(g)</code></pre>
<p><img src="/2021/05/10/heart-attack-risk-analysis/index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The covariance matrix above shows heart disease to be positively correlated with chest pain, the maximum heart rate achieved, and the incline type of exercise during the testing segment; and negatively correlated with exercise induced angina, and ST depression induced by exercise. I expect any machine learning model to take these correlations into account.</p>
</div>
<div id="age-distribution" class="section level2">
<h2>Age distribution</h2>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(age)) +
  geom_histogram(alpha = 0.5, fill = &quot;dodgerblue&quot;,binwidth = 5)+
  geom_vline(xintercept = mean(heart$age),lty = 2)</code></pre>
<p><img src="/2021/05/10/heart-attack-risk-analysis/index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(age))+
  geom_density()+
  geom_vline(xintercept = mean(heart$age),lty = 2)</code></pre>
<p><img src="/2021/05/10/heart-attack-risk-analysis/index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The observations within the dataset tends to skew older ages.</p>
</div>
<div id="sex-distribution" class="section level2">
<h2>Sex distribution</h2>
<pre class="r"><code>heart %&gt;% 
  count(sex)</code></pre>
<pre><code>## # A tibble: 2 x 2
##     sex     n
## * &lt;dbl&gt; &lt;int&gt;
## 1     0    96
## 2     1   207</code></pre>
<p>There are ~twice the amount of men featured in the dataset than women.</p>
</div>
<div id="chest-pain-distribution" class="section level2">
<h2>Chest pain distribution</h2>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(cp))+
  geom_histogram(fill = &quot;dodgerblue&quot;)+
  ggtitle(&quot;Chest pain&quot;, subtitle = &quot;chest pain type (1 = typical angina; 2 = atypical angina; 3 = non-anginal pain; 0 = asymptomatic)&quot;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/2021/05/10/heart-attack-risk-analysis/index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="resting-blood-pressure" class="section level2">
<h2>Resting blood pressure</h2>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(trtbps))+
  geom_histogram(fill = &quot;dodgerblue&quot;)+
  ggtitle(&quot;Resting blood pressure&quot;, subtitle = &quot;resting blood pressure (in mm Hg on admission to the hospital)&quot;)+
  geom_errorbarh(aes(xmin = 90, xmax = 120, y = 20),height = 4)+
  annotate(&quot;text&quot;,label = &quot;NHS &#39;normal&#39; range&quot;, x = 105, y = 22)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/2021/05/10/heart-attack-risk-analysis/index_files/figure-html/unnamed-chunk-10-1.png" width="672" />
There are a few observations with very high outlier resting blood pressure. According to the <a href="https://www.nhs.uk/common-health-questions/lifestyle/what-is-blood-pressure/">NHS</a>, a normal range for resting blood pressure in between 90 and 120.</p>
<pre class="r"><code>heart %&gt;% 
  filter(trtbps&gt;120) %&gt;% 
  count()</code></pre>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1   206</code></pre>
<p>The dataset skews heavily 67.99% outside of the ‘normal’ range for resting blood pressure.</p>
</div>
<div id="cholestoral-levels" class="section level2">
<h2>Cholestoral levels</h2>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(chol)) +
  geom_histogram(fill = &quot;dodgerblue&quot;) +
  ggtitle(&quot;Cholestoral levels&quot;,subtitle = &quot;serum cholestoral in mg/dl&quot;)+
  geom_errorbarh(aes(xmin = 125, xmax = 200, y = 20),height = 2) +
  annotate(&quot;text&quot;,label = &quot;&#39;normal&#39; range&quot;, x = 162.5, y = 22)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="/2021/05/10/heart-attack-risk-analysis/index_files/figure-html/unnamed-chunk-13-1.png" width="672" />
The normal range for cholesterol levels according to <a href="https://www.medicinenet.com/what_is_the_normal_range_for_cholesterol_levels/article.htm">medicinenet.com</a> is 125 to 200 mg/dL for men and women over age 20. Most of the observations fall outside of this range. There are very high outliers within the dataset with levels above 400 mg/dL.</p>
</div>
</div>
<div id="fitting-a-model-with-predictive-power" class="section level1">
<h1>Fitting a model with predictive power</h1>
<pre class="r"><code>i &lt;- sample(c(rep(0, 0.7 * (nrow(heart)+1)),
              rep(1, 0.3 * (nrow(heart)+1))))


heart_train &lt;- heart[i == 0, ]       
heart_test &lt;- heart[i == 1, ]     



y &lt;- heart_train$output
#colnames(heart)[1:ncol(heart)-1]
x &lt;- data.matrix(heart_train[, c(colnames(heart)[1:ncol(heart)-1])])


library(glmnet)</code></pre>
<pre><code>## Warning: package &#39;glmnet&#39; was built under R version 4.0.4</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 4.1-1</code></pre>
<pre class="r"><code>heart_model &lt;- cv.glmnet(x, y, alpha = 1)

best_lambda &lt;- heart_model$lambda.min

best_lambda</code></pre>
<pre><code>## [1] 0.000734635</code></pre>
<pre class="r"><code>plot(heart_model)</code></pre>
<p><img src="/2021/05/10/heart-attack-risk-analysis/index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code>best_model &lt;- glmnet(x, y, alpha = 1, lambda = best_lambda)
coef(best_model)</code></pre>
<pre><code>## 14 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                        s0
## (Intercept)  0.8292970527
## age          0.0028344044
## sex         -0.1560670932
## cp           0.1194732171
## trtbps      -0.0036498601
## chol        -0.0009306074
## fbs          0.1014638641
## restecg      0.0768308266
## thalachh     0.0049288254
## exng        -0.0523536559
## oldpeak     -0.0594957641
## slp          0.0224466989
## caa         -0.0862576893
## thall       -0.1748643612</code></pre>
<p>The fbs (fasting blood sugar) coefficient has been reduced to zero because of the nature of the Lasso regression model used. The Lasso regression is often implemented when there are lots of features and over-fitting a model may become a problem in producing an accurate model. Coefficients tending to zero are dropped from the model completely.</p>
<pre class="r"><code>heart_test_x &lt;- data.matrix(heart_test[, c(colnames(heart)[1:ncol(heart)-1])])
heart_test_y &lt;- heart_test$output
predictions &lt;- predict(best_model, s = best_lambda, newx = heart_test_x)
dim(predictions)</code></pre>
<pre><code>## [1] 91  1</code></pre>
<pre class="r"><code>dim(y)</code></pre>
<pre><code>## NULL</code></pre>
<pre class="r"><code>sst &lt;- sum((y - mean(y))^2)
sse &lt;- sum((predictions - heart_test_y)^2)

#find R-Squared
rsq &lt;- 1 - sse/sst
rsq</code></pre>
<pre><code>## [1] 0.7347842</code></pre>
<p>The R-squared turns out to be 0.7348. That is, the best model was able to explain 73.48% of the variation in the response values of the training data.</p>
<pre class="r"><code>full_results &lt;- cbind(data.frame(heart_test_y),predictions, heart_test_x) %&gt;% 
  rename(&quot;prediction&quot; = &quot;1&quot;,
         &quot;output&quot; = &quot;heart_test_y&quot;)



full_results</code></pre>
<pre><code>##    output   prediction age sex cp trtbps chol fbs restecg thalachh exng oldpeak
## 1       1  0.993238898  63   1  3    145  233   1       0      150    0     2.3
## 2       1  0.775214988  57   1  0    140  192   0       1      148    0     0.4
## 3       1  0.672401689  56   0  1    140  294   0       0      153    0     1.3
## 4       1  0.684501942  44   1  1    120  263   0       1      173    0     0.0
## 5       1  0.713915444  52   1  2    172  199   1       1      162    0     0.5
## 6       1  0.582104858  54   1  0    140  239   0       1      160    0     1.2
## 7       1  0.919099124  48   0  2    130  275   0       1      139    0     0.2
## 8       1  0.543351300  43   1  0    150  247   0       1      171    0     1.5
## 9       1  0.720303677  42   1  0    140  226   0       1      178    0     0.0
## 10      1  0.787668832  40   1  3    140  199   0       1      178    1     1.4
## 11      1  0.790035891  65   0  2    140  417   1       0      157    0     0.8
## 12      1  1.011265751  41   0  1    105  198   0       1      168    0     0.0
## 13      1  0.638393060  54   1  2    125  273   0       0      152    0     0.5
## 14      1  0.540217576  54   1  2    150  232   0       0      165    0     1.6
## 15      1  0.774281353  48   1  1    130  245   0       0      180    0     0.2
## 16      1  0.741854394  53   0  0    138  234   0       0      160    0     0.0
## 17      1  1.243952533  44   0  2    108  141   0       1      175    0     0.6
## 18      1  0.746083692  45   1  0    115  260   0       0      185    0     0.0
## 19      1  1.080745614  34   1  3    118  182   0       0      174    0     0.0
## 20      1  0.634292187  57   0  0    128  303   0       0      159    0     0.0
## 21      1  0.972508773  71   0  2    110  265   1       0      130    0     0.0
## 22      1  1.359321332  52   1  3    118  186   0       0      190    0     0.0
## 23      1  0.883639482  45   0  1    130  234   0       0      175    0     0.6
## 24      1  0.884595946  44   1  1    120  220   0       1      170    0     0.0
## 25      1  0.933344564  62   0  0    124  209   0       1      163    0     0.0
## 26      1  1.097526405  43   0  2    122  213   0       1      165    0     0.2
## 27      1  1.062498831  52   1  1    128  205   1       1      184    0     0.0
## 28      1  0.638832370  58   1  2    105  240   0       0      154    1     0.6
## 29      1  0.567782558  42   0  0    102  265   0       0      122    0     0.6
## 30      1  0.504824544  67   0  2    115  564   0       0      160    0     1.6
## 31      1  1.053776719  54   0  2    110  214   0       1      158    0     1.6
## 32      1  0.109902257  53   1  0    142  226   0       0      111    1     0.0
## 33      1  0.637598209  43   1  2    130  315   0       1      162    0     1.9
## 34      1  0.735830697  42   1  3    148  244   0       0      178    0     0.8
## 35      1  0.238144756  59   1  3    178  270   0       0      145    0     4.2
## 36      1  0.976059648  50   1  2    129  196   0       1      163    0     0.0
## 37      1  0.930458944  50   0  1    120  244   0       1      162    0     1.1
## 38      1  0.688150597  64   0  2    140  313   0       1      133    0     0.2
## 39      1  0.587938603  43   1  0    110  211   0       1      161    0     0.0
## 40      1  1.016835937  41   0  2    112  268   0       0      172    1     0.0
## 41      1  0.678686679  47   1  0    112  204   0       1      143    0     0.1
## 42      1  0.814842191  41   1  1    110  235   0       1      153    0     0.0
## 43      1  0.818761701  49   0  0    130  269   0       1      163    0     0.0
## 44      1  0.794351907  62   1  1    128  208   1       0      140    0     0.0
## 45      1  1.148234629  60   0  3    150  240   0       1      171    0     0.9
## 46      1  0.900549541  42   1  2    130  180   0       1      150    0     0.0
## 47      1  0.594982624  56   1  1    130  221   0       0      163    0     0.0
## 48      1  0.850174427  56   1  1    120  240   0       1      169    0     0.0
## 49      1  0.823398843  55   0  1    132  342   0       1      166    0     1.2
## 50      0  0.227607864  53   1  0    140  203   1       0      155    1     3.1
## 51      0  0.832816331  56   1  2    130  256   1       0      142    1     0.6
## 52      0  0.634945524  48   1  1    110  229   0       1      168    0     1.0
## 53      0  0.609060577  58   1  1    120  284   0       0      160    0     1.8
## 54      0  0.118104611  40   1  0    110  167   0       0      114    1     2.0
## 55      0  0.381264850  60   1  0    117  230   1       1      160    1     1.4
## 56      0  0.175440341  54   1  0    120  188   0       1      113    0     1.4
## 57      0  0.465660571  67   1  0    125  254   1       1      163    0     0.2
## 58      0 -0.106815616  62   1  0    120  267   0       1       99    1     1.8
## 59      0  0.694438563  44   1  0    110  197   0       0      177    0     0.0
## 60      0 -0.169127316  62   0  0    160  164   0       0      145    0     6.2
## 61      0  0.156260424  60   0  0    150  258   0       0      157    0     2.6
## 62      0  0.421751401  59   1  0    140  177   0       1      162    1     0.0
## 63      0  0.342610295  39   1  0    118  219   0       1      140    0     1.2
## 64      0  0.417929281  56   1  0    125  249   1       0      144    1     1.2
## 65      0  0.190854564  43   0  0    132  341   1       0      136    1     3.0
## 66      0  0.912019611  65   1  3    138  282   1       0      174    0     1.4
## 67      0  0.141781134  70   1  0    145  174   0       1      125    1     2.6
## 68      0  0.580026015  59   1  3    170  288   0       0      159    0     0.2
## 69      0  0.410702607  64   1  2    125  309   0       1      131    1     1.8
## 70      0 -0.144158456  57   1  0    165  289   1       0      124    0     1.0
## 71      0  0.002524381  55   1  0    160  289   0       0      145    1     0.8
## 72      0 -0.094102093  70   1  0    130  322   0       0      109    0     2.4
## 73      0  0.091837512  70   1  2    160  269   0       1      112    1     2.9
## 74      0 -0.176559346  57   1  0    152  274   0       1       88    1     1.2
## 75      0  0.280499860  56   1  0    132  184   0       0      105    1     2.1
## 76      0  0.017590450  56   0  0    134  409   0       0      150    1     1.9
## 77      0  0.116234611  50   1  0    144  200   0       0      126    1     0.9
## 78      0  0.679696558  38   1  3    120  231   0       1      182    1     3.8
## 79      0  0.613905129  63   0  0    108  269   0       1      169    1     1.8
## 80      0  0.455436251  66   1  0    112  212   0       0      132    1     0.1
## 81      0  0.172318795  55   0  0    180  327   0       2      117    1     3.4
## 82      0  0.491545207  49   1  2    118  149   0       0      126    0     0.8
## 83      0  0.360260368  52   1  0    125  212   0       1      168    0     1.0
## 84      0  0.533039830  57   1  1    124  261   0       1      141    0     0.3
## 85      0  1.021381713  52   1  0    128  204   1       1      156    1     1.0
## 86      0  0.885842723  59   1  2    126  218   1       1      134    0     2.2
## 87      0  0.593519201  57   1  1    154  232   0       0      164    0     0.0
## 88      0  0.421450366  61   1  0    148  203   0       1      161    0     0.0
## 89      0  0.539594792  67   1  2    152  212   0       0      150    0     0.8
## 90      0  0.595463414  44   1  0    120  169   0       1      144    1     2.8
## 91      0  0.169892723  57   1  0    130  131   0       1      115    1     1.2
##    slp caa thall
## 1    0   0     1
## 2    1   0     1
## 3    1   0     2
## 4    2   0     3
## 5    2   0     3
## 6    2   0     2
## 7    2   0     2
## 8    2   0     2
## 9    2   0     2
## 10   2   0     3
## 11   2   1     2
## 12   2   1     2
## 13   0   1     2
## 14   2   0     3
## 15   1   0     2
## 16   2   0     2
## 17   1   0     2
## 18   2   0     2
## 19   2   0     2
## 20   2   1     2
## 21   2   1     2
## 22   1   0     1
## 23   1   0     2
## 24   2   0     2
## 25   2   0     2
## 26   1   0     2
## 27   2   0     2
## 28   1   0     3
## 29   1   0     2
## 30   1   0     3
## 31   1   0     2
## 32   2   0     3
## 33   2   1     2
## 34   2   2     2
## 35   0   0     3
## 36   2   0     2
## 37   2   0     2
## 38   2   0     3
## 39   2   0     3
## 40   2   0     2
## 41   2   0     2
## 42   2   0     2
## 43   2   0     2
## 44   2   0     2
## 45   2   0     2
## 46   2   0     2
## 47   2   0     3
## 48   0   0     2
## 49   2   0     2
## 50   0   0     3
## 51   1   1     1
## 52   0   0     3
## 53   1   0     2
## 54   1   0     3
## 55   2   2     3
## 56   1   1     3
## 57   1   2     3
## 58   1   2     3
## 59   2   1     2
## 60   0   3     3
## 61   1   2     3
## 62   2   1     3
## 63   1   0     3
## 64   1   1     2
## 65   1   0     3
## 66   1   1     2
## 67   0   0     3
## 68   1   0     3
## 69   1   0     3
## 70   1   3     3
## 71   1   1     3
## 72   1   3     2
## 73   1   1     3
## 74   1   1     3
## 75   1   1     1
## 76   1   2     3
## 77   1   0     3
## 78   1   0     3
## 79   1   2     2
## 80   2   1     2
## 81   1   0     2
## 82   2   3     2
## 83   2   2     3
## 84   2   0     3
## 85   1   0     0
## 86   1   1     1
## 87   2   1     2
## 88   2   1     3
## 89   1   0     3
## 90   0   0     1
## 91   1   1     3</code></pre>
<pre class="r"><code>confusion_matrix &lt;- full_results %&gt;% 
  mutate(correct_prediction = ifelse(output == round(prediction,0),&quot;CORRECT&quot;,&quot;INCORRECT&quot;))</code></pre>
<pre class="r"><code>(cf &lt;- confusion_matrix %&gt;% 
  count(correct_prediction))</code></pre>
<pre><code>##   correct_prediction  n
## 1            CORRECT 75
## 2          INCORRECT 16</code></pre>
<p>The lasso regression is correct for 82.42% of the testing observations. test</p>
</div>

    </div>
  </article>

  


</main>

      <footer class="footer">
        <ul class="footer-links">
          <li>
            <a href="/index.xml" type="application/rss+xml" target="_blank">RSS feed</a>
          </li>
          <li>
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/images/hugo-logo.png" alt="Img link to Hugo website" width="22" height="22"></a>
          </li>
        </ul>
      </footer>

    </div>
    



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>



<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/r.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/yaml.min.js"></script>
<script>hljs.configure({languages: []}); hljs.initHighlightingOnLoad();</script>



    
<script src="/js/math-code.js"></script>
<script async src="//cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML"></script>


    
  </body>
</html>

