---
title: "Fast Track Data/AI Graduate Programme"
subtitle: "Covering Letter"
author: ""
date: "25/05/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


My background is in Accounting and Finance with an MSc (Distinction) and a BSc (First-class). The masters programme provided me with an appreciation for data, the philosophy of science, and a strong interest in applying statistical techniques. Data and statistical heavy modules include statistical methods, research methods, financial econometrics, among general mathematical applications in finance.

I am excited for the opportunity that this programme provides. It looks to be an excellent way to combine what I have learnt and my interests into an excellent foundation for a career in data science.

Since graduation, I have undertook courses provided by the Bangor University Doctoral School which I gained new skills in statistical programming as well as confidence in my ability to interrogate data and extract meaning. A handful of intensive courses from Jumping Rivers provided an excellent introduction to the R statistical programming language aimed to train students to become 'advanced beginners' using R for data science. The courses include an introduction to R, data manipulation, statistical modelling in R, R functional programming, and advanced graphics in R. These courses provided me with the basics as well as the confidence to explore packages on CRAN to discover what else I could do with R. I have also picked up practical skills in Python, and SQL throughout various courses. I really enjoy learning new tools as well as seeing what I can build with them, and I see this as a fun hobby. 

Since graduation, I have been working on how best to use R as well as machine learning packages such as caret. To further my interest and see what I could build in R, as well as providing a useful resource to store snippets of code, I built a website in R using the blogdown package, of which is found at RoyWilson.UK. I have also assisted my brother with his research into high entropy alloys by building an interactive dashboard in R shiny which calculates thermophysical properties and the thermal expansion coefficient quickly and with ease for the user. This dashboard can be found at RoyWilson.UK/HEA/.

I see myself finding a lot of success on the Data/AI Fast Track Graduate programme as it looks to be the formal structure that I have been looking for to fill in any gaps in my knowledge and to provide confidence in my ability that I will be learning cutting-edge and 

Sincerely,

Roy Wilson