---
title: "Untitled"
author: "Roy Wilson"
date: "26/08/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
* Jumping Rivers R courses
* built website roywilson.uk
* interactive dashboard R shiny thermal expansion RoyWilson.UK/HEA.
* Fan of the TidyTuesday project.
* Accounting and Finance MSc BSc 
* Python and SQL
* Shuffle.py





* business/data/analyst career goal in wales.

skills/projects

1. 50

I am pleased to apply for the data/AI fast track graduate programme with 


2. 125

Courses for the R programming language from Jumping Rivers funded by the Bangor Doctoral School sparked my interest in data science. These courses provided me with the confidence to interrogate and extract meaning from data, as well as the confidence to explore packages on CRAN to discover what else I could do with the language. I went on to build a website in R using the blogdown package which can be found at [RoyWilson.UK](https://RoyWilson.UK). This has proved useful in storing useful snippets of code that can be easily shared with others. I also built an interactive dashboard in R shiny which calculates the thermophysical properties and the thermal expansion coefficients of a selected alloy composition. This dashboard can be found at [RoyWilson.UK/HEA/](https://RoyWilson.UK/HEA/). I have also explored machine learning techniques found within the caret package and applied them to datasets from the TidyTuesday project with success in building predictive models. 

3. 125
These courses provided me with the confidence to interrogate and extract meaning from data, as well as the confidence to explore packages on CRAN to discover what else I could do with the language.

Soon after being introduced to python, I noticed that my brother and his supervisors were downloading molecular data from a supercomputer to then randomise in Excel, with each file being saved separately and re-uploaded to the supercomputer. I wrote a script in Python that takes in arguments from the user to automatically produce any number of randomised molecular data files that retain their unique structure. The script also organised the directories appropriately to aid in running calculations and produces these input files directly on the supercomputer without any need for downloading or uploading data. The ability to run this process directly from the command line interface has saved my brother and his research group countless hours by allowing them to focus on the science, rather than repetitive processes. 

4. 50