---
title: Metallurgical data
author: ~
date: '2020-07-03'
slug: compositional-analysis
categories: []
tags: []
---


```{r setup, include=FALSE, message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = T,warning = FALSE, message = FALSE)
```

```{r message=FALSE, warning=FALSE, include=FALSE}

#library(robustbase)
#library(energy)
#library(gtools)
library(compositions)
library(readr)
library(tidyverse)
library(neuralnet)
library(caret)
library(caretEnsemble)
library(httr)
library(readxl)
```

```{r}
divide01 <- function(x){
  return(x/100)
}

data <- read.csv("hardness.csv") %>% 
  mutate(Al=divide01(Al),
         Co=divide01(Co),
         Cr=divide01(Cr),
         Cu=divide01(Cu),
         Fe=divide01(Fe),
         Ni=divide01(Ni))
data_ordered <- read.csv("hardness.csv") %>% 
  mutate(Al=divide01(Al),
         Co=divide01(Co),
         Cr=divide01(Cr),
         Cu=divide01(Cu),
         Fe=divide01(Fe),
         Ni=divide01(Ni)) %>% 
  arrange(desc(hardness))

closed <- clo(data, parts = 1:6,total=100)
cx <- acomp(data, c("Al","Co","Cr"))
plot(cx)
xc <- acomp(data, c("Al","Co","Cr","Cu","Fe","Ni"))
xc_ordered <- acomp(data_ordered, c("Al","Co","Cr","Cu","Fe","Ni"))
plot(xc)
barplot.acomp(xc)

```

Order of hardness desc



```{r}

barplot.acomp(xc_ordered)
         
```

Possibly drop copper and nickel


```{r}
library(httr)
raw_dd <- read.table(text=content(GET("https://gist.githubusercontent.com/MrFlick/c1183c911bc5398105d4/raw/715868fba2d0d17a61a8081de17c468bbc525ab1/elements.txt")), sep=",", header=TRUE) %>%
  mutate(ElementName=ifelse(ElementName=="Sulfer","Sulfur",ElementName),
         ElementName=ifelse(ElementName=="Phosphorous","Phosphorus",ElementName),
         ElementName=ifelse(ElementName=="Flourine","Fluorine",ElementName))
data <- read_xlsx("melting_points.xlsx", sheet = 'Sheet2')
colnames(raw_dd) <- c(colnames(raw_dd)[1:7],"element",colnames(raw_dd)[9:13])

 

dd <- raw_dd %>%
  left_join(data, by = "element") %>%
  mutate(CTE_ppm=CTE*1000000,
         CTE_ppm=as.numeric(CTE_ppm),
         scaled_cte=CTE_ppm,
         scaled_cte=ifelse(scaled_cte>8,8,scaled_cte),
         scaled_cte=ifelse(scaled_cte<4.5,4.4,scaled_cte),
         new_structure=ifelse(crystal_structure %in% c("Body-centered Cubic","Face-centered Cubic","Simple Hexagonal"),crystal_structure,NA))

 

 

dd %>%
  ggplot(aes(Column,-Row)) +
  geom_tile(aes(fill=crystal_structure), color="black") +
  geom_text(aes(Column, -Row,label= symbol))+
  theme_void()+
  labs(
    fill = "Crystal Structure"
  ) +
  annotate("text", x = 7, y = 0.2, label = "Periodic Table of the elements", size = 5)

 

dd %>%
  count(crystal_structure)

 

(p<-dd %>%
  filter(!is.na(symbol)) %>%
  #filter(!crystal_structure %in% c("Base-centered Monoclinic","Centered Tetragonal")) %>%
  ggplot(aes(Column, -Row))+
  geom_tile(aes(fill=scaled_cte), color="black",size=1) +
  geom_rect(aes(xmin=Column-0.3,xmax=Column+0.3,ymin=-Row-0.2,ymax=-Row+0.3,colour=new_structure),size=1,lty=1,fill="black")+
    #geom_text(aes(label="",colour=new_structure), na.rm = T,size=12,nudge_y = 0.3)+
  geom_text(aes(label=symbol),colour="yellow",nudge_y = +0.05)+
  geom_text(aes(label=CTE_ppm),colour="black",nudge_y = -0.35)+
  scale_fill_gradient(low = "red",high = "green")+
  labs(fill = expression(paste("CTE", 10^6)),
    colour="") +
  annotate("text", x = 7, y = 0.2, label = "Periodic Table of the elements", size = 5))+
  theme_void()+
  theme(legend.position="bottom")+
  scale_colour_discrete(na.translate = F)


```



```{r}

f1 <- function(x){
  return(1/(16.6*3*(x+273)))
}


library(plotly)
library(ggrepel)
data %>% 
  ggplot(aes(mp, CTE, label=element))+
  geom_point()+
  stat_function(fun=f1)+
  lims(
    x=c(1500,4000),
    y=c(0,0.000025)
  )+
  theme(legend.position = "none")+
  ggrepel::geom_text_repel()+
  theme_classic()


```

