---
title: Coronavirus
author: ~
date: '2020-07-17'
slug: coronavirus
categories: []
tags: []
---

https://www.ecdc.europa.eu/en/publications-data/download-todays-data-geographic-distribution-covid-19-cases-worldwide

```{r setup, include=FALSE, message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

Libraries, reading in of the data and light tidying.

```{r}
library(tidyverse)
library(lubridate)
library(httr)
library(zoo)
library(plotly)
library(dplyr)
library(ggrepel)
library(gganimate)
library(gifski)
library(transformr)
library(tidyr)
library(ggthemes)


theme_set(theme_minimal())

covid_raw <- read.csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv", na.strings = "", fileEncoding = "UTF-8-BOM") %>% 
  rename("date" = dateRep,
         "country" = countriesAndTerritories,
         "code" = countryterritoryCode,
         "population2019" = popData2019,
         "continent" = continentExp,
         "cases_rate" = Cumulative_number_for_14_days_of_COVID.19_cases_per_100000)
```

Defining of the G8 and G20 nations

```{r}
#covid_data <- read.csv("covid_data.csv")

G8 <- c("FRA","DEU","ITA","JPN","GBR","USA","RUS","CDN")

G20 <- c("ARG","BRA","AUS","CAN","CHN","FRA","DEU","IND","IDN","ITA","JPN","KOR","MEX","RUS","SAU","ZAF","TUR","GBR","USA")

graph_colours <- c("cases_rate" = "orange","deaths" = "red", "Lockdown" = "dodgerblue", "Restrictions lifted" = "green")
graph_colours
```

Getting the data ready for use.

```{r}
covid <- covid_raw %>%
  mutate(date=dmy(date),
         country= case_when(
           country == "United_Kingdom" ~ "United Kingdom",
           country == "United_States_of_America" ~ "United States",
           TRUE ~ country
         )) %>% 
  mutate(country = sub("_"," ",country)) %>% 
  filter(cases_rate>-1,
         deaths > -1)
```

Creating dataframes specific to G8 and G20 nations.

```{r}
covid_g8 <- covid %>% 
  filter(code %in% c(G8))

covid_g20 <- covid %>% 
  filter(code %in% c(G20)) %>% 
  mutate(day = (date - min(covid$date))) %>%
  mutate(day = as.integer(parse_number(toString(day))))


add_critical_date <- function(date,country,label){
  
}

```

Lockdown date data from wikipedia
https://en.wikipedia.org/wiki/National_responses_to_the_COVID-19_pandemic#Lockdowns

This lockdown changes data is incomplete.

```{r}
dates <- readxl::read_excel("date_data.xlsx", col_names = FALSE)
colnames(dates) <- c("country","region","start","end")

dates <- dates %>%
  mutate(country = na.locf(country, fromLast = FALSE),
         country = str_trim(country),
        start = ymd(gsub("\\[.*\\]", "", start)),
        end = ymd(gsub("\\[.*\\]", "", end)))


critical_dates <- dates %>% 
  pivot_longer(cols = c("start","end"),names_to=c("event"),values_to="date") %>% 
  filter(!is.na(date)) %>% 
  select(-region) %>% 
  rename("label" = "event") %>% 
  mutate(label = case_when(label == "start" ~ "Lockdown",
                           label == "end" ~ "Restrictions lifted",
                           TRUE ~ label))



critical_dates <- critical_dates %>% 
  full_join(covid, by = c("date", "country")) %>% 
  filter(!is.na(cases_rate),
         !is.na(label))


```


Plotting our graphs.

```{r}
plot_country <- function(c){
  covid %>% 
  filter(country == toString(c)) %>%
  ggplot(aes(date, cases_rate)) +
  geom_line() +
  labs(
    title = paste(c, "cases per 100,000 people"),
    subtitle = paste("Current rate is ", round(
      covid %>% filter(country == toString(c)) %>% select(cases_rate) %>% head(1),
      2
    ),"", ""),
    x = "",
    y = "No. cases per 100,000 people",
    caption = "Source: https://opendata.ecdc.europa.eu/covid19/",
    colour = "Critical dates"
  ) +
  geom_point(data = critical_dates %>% filter(country==toString(c)), aes(date,cases_rate, colour = label),shape=18,size=4)+
  #geom_text_repel(data = critical_dates %>% filter(country==toString(c)),aes(x=date, y=cases_rate, label=label),size=3, angle = 90, nudge_y = 20)+
  scale_x_date(date_breaks = "1 month", date_minor_breaks = "1 week",
             date_labels = "%B")+
    scale_colour_manual(values = c("red","green"),aesthetics = c("colour"))+
  #scale_y_continuous(breaks = seq(0,max(max(covid %>% filter(country == toString(c)) %>% select(cases_rate))), floor(max(covid %>% filter(country == toString(c)) %>% select(cases_rate))/10)))+
    ggthemes::theme_fivethirtyeight()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "bottom")
}

plot_deaths <- function(c){
  covid %>% 
  filter(country == toString(c)) %>%
  ggplot(aes(date, deaths)) +
  geom_line() +
  labs(
    title = paste(c, "deaths"),
    subtitle = paste("Current daily deaths: ", round(
      covid %>% filter(country == toString(c)) %>% select(deaths) %>% head(1),
      2
    ),"", ""),
    x = "",
    y = "Daily mumber of deaths",
    caption = "Source: https://opendata.ecdc.europa.eu/covid19/",
    colour = "Critical dates"
  ) +
    geom_smooth(method = "gam",lty = 2, colour = "red",se=F)+
    geom_point(data = critical_dates %>% filter(country==toString(c)), aes(date,deaths, colour = label),shape=18,size=4)+
  scale_x_date(date_breaks = "1 month", date_minor_breaks = "1 week",
             date_labels = "%B")+
    scale_colour_manual(values = c("dodgerblue","yellow"),aesthetics = c("colour"))+
    ggthemes::theme_fivethirtyeight()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "bottom")
}




```


```{r}
covid_g8 %>% 
  ggplot(aes(date, cases_rate, colour = country))+
  geom_line()+
  theme(legend.position = "bottom")+
  labs(colour = "Country Code",
       x="",
       y="No. cases per 100,000 people",
       title = "Active covid-19 cases per 100,000 people in the G8")+
  scale_x_date(date_breaks = "1 month", date_minor_breaks = "1 week",
             date_labels = "%B")

covid_g20 %>% 
  ggplot(aes(date, cases_rate,colour = country))+
    geom_line()+
  theme(legend.position = "none")+
  geom_smooth(aes(group = 1), lty = 5, size = 1, colour = "black")+
  labs(colour = "Country Code",
       x="",
       y="No. cases per 100,000 people",
       title = "Active covid-19 cases per 100,000 people in the G20",
       caption = "Source: opendata.ecdc.europa.eu/covid19/")


ggplotly(
  covid_g20 %>%
    ggplot(aes(date, cases_rate, colour = country)) +
    geom_line() +
    theme(legend.position = "bottom") +
    geom_vline(xintercept = ymd(20200525)) +
  labs(
    colour = "Country Code",
    x = "",
    y = "No. cases per 100,000 people",
    title = "Active covid-19 cases per 100,000 people in the G20"
  )
)




```

```{r}
plot_country("United Kingdom")
plot_country("United States")
plot_country("France")
plot_country("Germany")
plot_country("Pakistan")
plot_country("Brazil")
plot_country("Algeria")
plot_country("Albania")


```



# Plotting country deaths

```{r}
covid %>% 
  mutate(country = fct_reorder(country, -deaths),
         country = fct_lump(country, 20)) %>% 
  group_by(country) %>% 
  mutate(deaths = max(deaths)) %>% 
  summarise(country,deaths) %>% 
  distinct_all() %>% 
  ggplot(aes(reorder(country,deaths), deaths, fill = country))+
  geom_col()+
  coord_flip()+
  theme(legend.position = "none")

ggplotly(covid %>% 
  group_by(continent) %>% 
  mutate(continent = fct_reorder(continent, -deaths),
         continent = fct_lump(continent, 20)) %>% 
  mutate(deaths = max(deaths)) %>% 
  #summarise(continent,deaths) %>% 
  distinct_all() %>% 
  ggplot(aes(reorder(continent,deaths), deaths, fill = reorder(country,deaths)))+
  geom_col()+
  coord_flip()+
  theme(legend.position = "none")+
    scale_y_continuous(labels = scales::number_format()))

plot_deaths("United Kingdom")
plot_deaths("United States")
plot_deaths("Brazil")
plot_deaths("Iraq")
plot_deaths("Iran")
plot_deaths("India")
plot_deaths("Pakistan")
plot_deaths("Afghanistan")
plot_deaths("Switzerland")
plot_deaths("France")
plot_deaths("Germany")
plot_deaths("South Korea")
plot_deaths("North Korea")
plot_deaths("Holy See")
plot_deaths("Russia")
plot_deaths("Japan")
plot_deaths("Italy")
plot_deaths("Turkey")
plot_deaths("South Africa")
plot_deaths("Spain")

covid %>% 
  arrange(-population2019) %>%
  distinct(country) %>% 
  view


df <- covid %>% 
  count(country, sort = TRUE)

countries <- df[[1]]

```


```{r}
plot_cases_deaths <- function(c){
  covid %>% 
  filter(country == toString(c)) %>%
  ggplot(aes(date, deaths)) +
  geom_line() +
  labs(
    title = paste(c, "deaths"),
    subtitle = paste("Current daily deaths: ", round(
      covid %>% filter(country == toString(c)) %>% select(deaths) %>% head(1),
      2
    ),"", ""),
    x = "",
    y = "Daily mumber of deaths",
    caption = "Source: https://opendata.ecdc.europa.eu/covid19/",
    colour = "Critical dates"
  ) +
    geom_smooth(method = "gam",lty = 2, colour = "red",se=F)+
    geom_point(data = critical_dates %>% filter(country==toString(c)), aes(date,deaths, colour = label),shape=18,size=4)+
  scale_x_date(date_breaks = "1 month", date_minor_breaks = "1 week",
             date_labels = "%B")+
    scale_colour_manual(values = c("dodgerblue","yellow"),aesthetics = c("colour"))+
    ggthemes::theme_solarized_2()+
  theme(panel.grid.major = element_blank(),
        panel.grid.minor.x = element_blank(),
        legend.position = "bottom")
}

values=c("red","orange","blue","green","purple")
plot_cases_deaths("United States")



covid %>% 
  filter(country == toString("United States")) %>%
    rename("Deaths" = "deaths","Active cases rate" = "cases_rate") %>% 
  full_join(critical_dates,by="date") %>% 
  pivot_longer(cols = c("Active cases rate",Deaths),names_to = "name01", values_to = "value")

covid %>% 
  count(country)
```



