---
title: Market Basket Analysis
author: ~
date: '2020-10-07'
slug: market-basket-analysis
categories: []
tags: []
---

```{r setup, include=FALSE, message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```

```{r}
library(tidyverse)
library(arulesViz)
library(lubridate)
library(arules)
library(RColorBrewer)
library(stringr)
library(tidyr)
```

Data sourced from Kaggle ``````https://www.kaggle.com/heeraldedhia/groceries-dataset?select=Groceries_dataset.csv``````


Association rules

$Rule: X \implies Y$

$$Support = \frac{freq(X, Y)}{N}$$

$$Confidence = \frac{freq(X, Y)}{freq(X)}$$

$$Lift = \frac{Support}{Supp(X)\times Supp(Y)}$$

APRIORI Algorithm

```{r}
transactions <- read.csv(file.path("data","basket.csv"))

df <- transactions %>%
  group_by(Member_number, Date) %>%
  summarise(items = str_c(itemDescription, collapse = ",")) %>% 
  mutate(n=str_count(items,",")+1)

max(df$n)

transactions %>% 
  count(itemDescription, sort = TRUE) %>% 
  head(5)

transactions %>% 
  count(itemDescription, sort = TRUE) %>% 
  tail(5)

```


# Utidying the dataset for use with the APRIORI algorithm in the "arules" package.

```{r}
basket <- transactions %>%
  group_by(Member_number, Date) %>%
  summarise(items = str_c(itemDescription, collapse = ",")) %>%
  ungroup() %>%
  select(items)


dim(basket)




basket <- basket %>% 
  separate(col = items, sep=",",into = c(paste(seq(1:11))))

#colnames(basket) <- NULL
basket
#write.csv(basket,file = file.path("data","basketitems.csv"))

#transaction_object <- read.transactions(file.path("data","basketitems.csv"),sep = ",")

transaction_object <- as(basket, "transactions")

summary(transaction_object)

# WIP
#colnames(transaction_object) <- colnames(transaction_object) %>% 
#  str_remove(pattern = "[123456789][=]")

colnames(transaction_object)

? discretizeDF
itemFrequencyPlot(transaction_object,topN=30,type="absolute",col=brewer.pal(8,'Pastel1'), main="Absolute Item Frequency Plot")

itemFrequencyPlot(transaction_object,topN=30,type="relative",col=brewer.pal(8,'Pastel1'), main="Absolute Item Frequency Plot")
?regex
rules <- apriori(transaction_object, parameter = list(supp=0.0001, conf=0.15,minlen=2))
rules <- sort(rules, by='confidence', decreasing = TRUE)
rules[1:50] %>% 
  inspect()



```


