---
title: Time-series and yfinance api
author: ~
date: '2020-07-07'
slug: time-series-and-yfinance-api
categories: []
tags: []
---

Python integration using the reticulate package.

yFinance api from https://pypi.org/project/yfinance/

Python exchange rate api from www.exchangerate-api.com

```{r setup, include=FALSE, message=FALSE,warning=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning = FALSE, message = FALSE)
```


```{r}
library(reticulate)
library(tidyquant)
library(timetk)
library(sweep)
library(forecast)
library(tidyverse)
library(bbplot)
library(lubridate)
library(Mcomp)
library(smooth)
library(broom)

py_config()

use_miniconda()
```



```{python}
import yfinance as yf

  

def yfinance01(ticker,period):
    g = yf.Ticker(ticker)
    data=g.history(period=period)
    return data

```



```{r functions}
fixcol01 <- function(g){
  g <- cbind(date = rownames(g), g)
  rownames(g) <- 1:nrow(g)
  return(g)
}

retrieve01 <- function(ticker,period="max"){
  g <- py$yfinance01(ticker,period)
  g <- fixcol01(g)
  g <- g %>% 
    select(date, Close)%>% 
    mutate(date=as_date(ymd(date)))
  colnames(g) <- c("date", ticker)
  return(g)
}

plotting01 <- function(ticker, period="max"){
  g <- retrieve01(ticker, period)
  plot <- g %>%  
    ggplot(aes(date, get(ticker), group=1))+
    geom_point(shape=".")+
    labs(title=ticker)+
    theme_void()+
    scale_y_continuous()+
    theme(axis.text = element_text())+
    geom_line(size=1)
  return(plot)
}

multiplot <- function(..., period = "1max",length=1000){
  x <- list(...)
  y <- data.frame("date"=c(seq(today()-length,by="day",length.out = length)))
  for (val in x){
    y <- left_join(y,retrieve01(val, period),by="date")
  }
  h <- y %>%
    pivot_longer(cols = c(...),names_to = "ticker",values_to = "price")
  return(h)
}


```

### Retail industry

M&S Morrisons Tesco Walmart




```{r}
(data <- multiplot("WMT","MRW.L","TSCO.L","MKS.L", period = "max",length = 12000) %>% 
  filter(!is.na(price)) %>% 
  ggplot()+
  geom_line(aes(date, price, colour = ticker))+
  theme_void()+
  labs(colour = "Ticker",
       title="Retail industry - 30 year overview")+
  theme(axis.text = element_text(),
        legend.position = "bottom"))

(data <- multiplot("WMT","MRW.L","TSCO.L","MKS.L", period = "max",length = 3650) %>% 
  filter(!is.na(price)) %>% 
  ggplot()+
  geom_line(aes(date, price, colour = ticker))+
  geom_smooth(colour = "black", lty = 2, aes(date, price), se = F)+
  theme_void()+
  labs(colour = "Ticker",
       title = "Retail industry - 10 year overview")+
  theme(axis.text = element_text(),
        legend.position = "bottom"))
```


taking log prices

```{r}
(data <- multiplot("WMT","MRW.L","TSCO.L","MKS.L", period = "max",length = 3650) %>% 
  filter(!is.na(price)) %>% 
  mutate(price=log(price)) %>% 
  ggplot()+
  geom_point(aes(date, price, colour = ticker), shape=".")+
  geom_smooth(aes(date, price, colour = ticker), se = F)+
  stat_smooth(aes(date, price),se = F,geom="line",lty=4)+
  theme_void()+
  labs(colour = "Ticker")+
  theme(axis.text = element_text(),
        legend.position = "bottom"))


(data <- multiplot("WMT","MRW.L","TSCO.L","MKS.L", period = "max",length = 15000) %>% 
  filter(!is.na(price),
         price>1) %>% 
  mutate(price=log(price)) %>% 
  ggplot()+
  geom_line(aes(date, price, colour = ticker))+
  geom_smooth(colour = "black", lty = 2, aes(date, price), se = F)+
  geom_smooth(aes(date, price, colour = ticker),se = F)+
  theme_void()+
  labs(colour = "Ticker")+
  theme(axis.text = element_text(),
        legend.position = "bottom"))
  

```

```{r}
library(plotly)
ggplotly(data)
```



