---
title: Tidy Models
author: 'Roy Wilson'
date: '2021-08-05'
slug: tidy-models
output: 
  html_document:
    toc: true
categories: []
tags: []
---

# Exploring machine learning models using the Tidy Models package

\tableofcontents

Following the guidance from https://www.tidymodels.org/start/models/

```{r message=FALSE, warning=FALSE}
library(tidymodels)  # for the parsnip package, along with the rest of tidymodels
library(tidyverse)       
library(broom.mixed) # for converting Bayesian models to tidy tibbles
library(dotwhisker)  # for visualizing regression results


```

## Reading in the Urchin dataset

```{r}
urchins <- read_csv("https://tidymodels.org/start/models/urchins.csv")  |>  
  setNames(c("food_regime", "initial_volume", "width")) |>  
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))

glimpse(urchins)
```
## Getting a visual overview of the dataset

```{r}
urchins |> 
  ggplot(aes(initial_volume, width, colour = food_regime))+
  geom_point()+
  geom_smooth(method = lm, se = FALSE)+
  theme_minimal()
```

## Building a predictive linear model

```{r}
linear.model <- linear_reg()  |>  
  parsnip::set_engine("lm")

linear.fit <- linear.model |> 
  parsnip::fit(width ~ initial_volume * food_regime, data = urchins)

linear.fit |> 
  tidy()


tidy(linear.fit) |> 
  ggplot(aes(term, estimate, ymin = estimate - std.error, ymax = estimate + std.error, colour = term)) +
  geom_errorbar()+
  geom_point()+
  coord_flip()+
  theme_bw()+
  theme(legend.position = "none")
  
```

## Using the model to make predictions

```{r}
new_data <- expand.grid(initial_volume = 35, 
                          food_regime = c("Initial", "Low", "High"))

prediction <- predict(linear.fit, new_data = new_data)
prediction
```
```{r}
prediction_conf <- predict(linear.fit, 
                         new_data = new_data, 
                         type = "conf_int")
prediction_conf
```
```{r}
plotting <- new_data |> 
  bind_cols(prediction) |> 
  bind_cols(prediction_conf)

plotting

plotting |> 
  ggplot(aes(x = food_regime, y = .pred, colour = food_regime))+
  geom_point()+
  geom_errorbar(aes(ymin = .pred_lower, ymax = .pred_upper), width = 0.3)+
  theme_light()+
  theme(legend.position = 'none')+
  labs(title = "Size of Sea Urchins",
       y = "size of Urchin",
       x  = "Food Regime")
```

## Using other engines

```{r}

```



