---
title: Heart attack risk analysis
author: ''
date: '2021-05-10'
slug: heart-attack-risk-analysis
categories: []
tags: []
---

<script src="{{< blogdown/postref >}}index_files/header-attrs/header-attrs.js"></script>


<pre class="r"><code>library(tidyverse)
library(readr)
library(broom)
theme_set(theme_minimal())

heart &lt;- read_csv(&quot;heart.csv&quot;)</code></pre>
<p>The dataset can be found on <a href="https://www.kaggle.com/rashikrahmanpritom/heart-attack-analysis-prediction-dataset">kaggle</a></p>
<pre class="r"><code>glimpse(heart)</code></pre>
<pre><code>## Rows: 303
## Columns: 14
## $ age      &lt;dbl&gt; 63, 37, 41, 56, 57, 57, 56, 44, 52, 57, 54, 48, 49, 64, 58, 5~
## $ sex      &lt;dbl&gt; 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1~
## $ cp       &lt;dbl&gt; 3, 2, 1, 1, 0, 0, 1, 1, 2, 2, 0, 2, 1, 3, 3, 2, 2, 3, 0, 3, 0~
## $ trtbps   &lt;dbl&gt; 145, 130, 130, 120, 120, 140, 140, 120, 172, 150, 140, 130, 1~
## $ chol     &lt;dbl&gt; 233, 250, 204, 236, 354, 192, 294, 263, 199, 168, 239, 275, 2~
## $ fbs      &lt;dbl&gt; 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0~
## $ restecg  &lt;dbl&gt; 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1~
## $ thalachh &lt;dbl&gt; 150, 187, 172, 178, 163, 148, 153, 173, 162, 174, 160, 139, 1~
## $ exng     &lt;dbl&gt; 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0~
## $ oldpeak  &lt;dbl&gt; 2.3, 3.5, 1.4, 0.8, 0.6, 0.4, 1.3, 0.0, 0.5, 1.6, 1.2, 0.2, 0~
## $ slp      &lt;dbl&gt; 0, 0, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 1, 2, 0, 2, 2, 1~
## $ caa      &lt;dbl&gt; 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0~
## $ thall    &lt;dbl&gt; 1, 2, 2, 2, 2, 1, 2, 3, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3~
## $ output   &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1~</code></pre>
<p>N = 303</p>
<div id="explanation-of-features" class="section level1">
<h1>Explanation of features</h1>
<ol style="list-style-type: decimal">
<li>age - age in years</li>
<li>sex - sex (1 = male; 0 = female)</li>
<li>cp - chest pain type (1 = typical angina; 2 = atypical angina; 3 = non-anginal pain; 0 = asymptomatic)</li>
<li>trestbps - resting blood pressure (in mm Hg on admission to the hospital)</li>
<li>chol - serum cholestoral in mg/dl</li>
<li>fbs - fasting blood sugar &gt; 120 mg/dl (1 = true; 0 = false)</li>
<li>restecg - resting electrocardiographic results (1 = normal; 2 = having ST-T wave abnormality; 0 = hypertrophy)</li>
<li>thalach - maximum heart rate achieved</li>
<li>exang - exercise induced angina (1 = yes; 0 = no)</li>
<li>oldpeak - ST depression induced by exercise relative to rest</li>
<li>slope - the slope of the peak exercise ST segment (2 = upsloping; 1 = flat; 0 = downsloping)</li>
<li>ca - number of major vessels (0-3) colored by flourosopy</li>
<li>thal - 2 = normal; 1 = fixed defect; 3 = reversable defect</li>
<li>output - diagnosis of heart disease</li>
</ol>
<p>It is my understanding that the ST is a specific interval of time during an electrocardiogram stress test.</p>
</div>
<div id="exploring-the-dataset" class="section level1">
<h1>Exploring the dataset</h1>
<pre class="r"><code>heart %&gt;% 
  count(output)</code></pre>
<pre><code>## # A tibble: 2 x 2
##   output     n
## *  &lt;dbl&gt; &lt;int&gt;
## 1      0   138
## 2      1   165</code></pre>
<p>The dataset represents 54.46% of people who suffer with heart disease.</p>
<div id="covariance-matrix" class="section level2">
<h2>Covariance matrix</h2>
<pre class="r"><code>g &lt;- cor(heart)

corrplot::corrplot(g)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>The covariance matrix above shows heart disease to be positively correlated with chest pain, the maximum heart rate achieved, and the incline type of exercise during the testing segment; and negatively correlated with exercise induced angina, and ST depression induced by exercise. I expect any machine learning model to take these correlations into account.</p>
</div>
<div id="age-distribution" class="section level2">
<h2>Age distribution</h2>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(age)) +
  geom_histogram(alpha = 0.5, fill = &quot;dodgerblue&quot;,binwidth = 5)+
  geom_vline(xintercept = mean(heart$age),lty = 2)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(age))+
  geom_density()+
  geom_vline(xintercept = mean(heart$age),lty = 2)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
<p>The observations within the dataset tends to skew older ages.</p>
</div>
<div id="sex-distribution" class="section level2">
<h2>Sex distribution</h2>
<pre class="r"><code>heart %&gt;% 
  count(sex)</code></pre>
<pre><code>## # A tibble: 2 x 2
##     sex     n
## * &lt;dbl&gt; &lt;int&gt;
## 1     0    96
## 2     1   207</code></pre>
<p>There are ~twice the amount of men featured in the dataset than women.</p>
</div>
<div id="chest-pain-distribution" class="section level2">
<h2>Chest pain distribution</h2>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(cp))+
  geom_histogram(fill = &quot;dodgerblue&quot;)+
  ggtitle(&quot;Chest pain&quot;, subtitle = &quot;chest pain type (1 = typical angina; 2 = atypical angina; 3 = non-anginal pain; 0 = asymptomatic)&quot;)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-9-1.png" width="672" /></p>
</div>
<div id="resting-blood-pressure" class="section level2">
<h2>Resting blood pressure</h2>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(trtbps))+
  geom_histogram(fill = &quot;dodgerblue&quot;)+
  ggtitle(&quot;Resting blood pressure&quot;, subtitle = &quot;resting blood pressure (in mm Hg on admission to the hospital)&quot;)+
  geom_errorbarh(aes(xmin = 90, xmax = 120, y = 20),height = 4)+
  annotate(&quot;text&quot;,label = &quot;NHS &#39;normal&#39; range&quot;, x = 105, y = 22)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-10-1.png" width="672" />
There are a few observations with very high outlier resting blood pressure. According to the <a href="https://www.nhs.uk/common-health-questions/lifestyle/what-is-blood-pressure/">NHS</a>, a normal range for resting blood pressure in between 90 and 120.</p>
<pre class="r"><code>heart %&gt;% 
  filter(trtbps&gt;120) %&gt;% 
  count()</code></pre>
<pre><code>## # A tibble: 1 x 1
##       n
##   &lt;int&gt;
## 1   206</code></pre>
<p>The dataset skews heavily 67.99% outside of the ‘normal’ range for resting blood pressure.</p>
</div>
<div id="cholestoral-levels" class="section level2">
<h2>Cholestoral levels</h2>
<pre class="r"><code>heart %&gt;% 
  ggplot(aes(chol)) +
  geom_histogram(fill = &quot;dodgerblue&quot;) +
  ggtitle(&quot;Cholestoral levels&quot;,subtitle = &quot;serum cholestoral in mg/dl&quot;)+
  geom_errorbarh(aes(xmin = 125, xmax = 200, y = 20),height = 2) +
  annotate(&quot;text&quot;,label = &quot;&#39;normal&#39; range&quot;, x = 162.5, y = 22)</code></pre>
<pre><code>## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-13-1.png" width="672" />
The normal range for cholesterol levels according to <a href="https://www.medicinenet.com/what_is_the_normal_range_for_cholesterol_levels/article.htm">medicinenet.com</a> is 125 to 200 mg/dL for men and women over age 20. Most of the observations fall outside of this range. There are very high outliers within the dataset with levels above 400 mg/dL.</p>
</div>
</div>
<div id="fitting-a-model-with-predictive-power" class="section level1">
<h1>Fitting a model with predictive power</h1>
<pre class="r"><code>i &lt;- sample(c(rep(0, 0.7 * (nrow(heart)+1)),
              rep(1, 0.3 * (nrow(heart)+1))))


heart_train &lt;- heart[i == 0, ]       
heart_test &lt;- heart[i == 1, ]     



y &lt;- heart_train$output
#colnames(heart)[1:ncol(heart)-1]
x &lt;- data.matrix(heart_train[, c(colnames(heart)[1:ncol(heart)-1])])


library(glmnet)</code></pre>
<pre><code>## Warning: package &#39;glmnet&#39; was built under R version 4.0.4</code></pre>
<pre><code>## Loading required package: Matrix</code></pre>
<pre><code>## 
## Attaching package: &#39;Matrix&#39;</code></pre>
<pre><code>## The following objects are masked from &#39;package:tidyr&#39;:
## 
##     expand, pack, unpack</code></pre>
<pre><code>## Loaded glmnet 4.1-1</code></pre>
<pre class="r"><code>heart_model &lt;- cv.glmnet(x, y, alpha = 1)

best_lambda &lt;- heart_model$lambda.min

best_lambda</code></pre>
<pre><code>## [1] 0.01425797</code></pre>
<pre class="r"><code>plot(heart_model)</code></pre>
<p><img src="{{< blogdown/postref >}}index_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<pre class="r"><code>best_model &lt;- glmnet(x, y, alpha = 1, lambda = best_lambda)
coef(best_model)</code></pre>
<pre><code>## 14 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                       s0
## (Intercept)  0.722157522
## age          .          
## sex         -0.144675760
## cp           0.098243222
## trtbps      -0.001457489
## chol         .          
## fbs          .          
## restecg      0.010530529
## thalachh     0.003050254
## exng        -0.131697880
## oldpeak     -0.096438269
## slp          0.042341967
## caa         -0.078987023
## thall       -0.124581144</code></pre>
<p>The fbs (fasting blood sugar) coefficient has been reduced to zero because of the nature of the Lasso regression model used. The Lasso regression is often implemented when there are lots of features and over-fitting a model may become a problem in producing an accurate model. Coefficients tending to zero are dropped from the model completely.</p>
<pre class="r"><code>heart_test_x &lt;- data.matrix(heart_test[, c(colnames(heart)[1:ncol(heart)-1])])
heart_test_y &lt;- heart_test$output
predictions &lt;- predict(best_model, s = best_lambda, newx = heart_test_x)
dim(predictions)</code></pre>
<pre><code>## [1] 91  1</code></pre>
<pre class="r"><code>dim(y)</code></pre>
<pre><code>## NULL</code></pre>
<pre class="r"><code>sst &lt;- sum((y - mean(y))^2)
sse &lt;- sum((predictions - heart_test_y)^2)

#find R-Squared
rsq &lt;- 1 - sse/sst
rsq</code></pre>
<pre><code>## [1] 0.8043719</code></pre>
<p>The R-squared turns out to be 0.8044. That is, the best model was able to explain 80.44% of the variation in the response values of the training data.</p>
<pre class="r"><code>full_results &lt;- cbind(data.frame(heart_test_y),predictions, heart_test_x) %&gt;% 
  rename(&quot;prediction&quot; = &quot;1&quot;,
         &quot;output&quot; = &quot;heart_test_y&quot;)



full_results</code></pre>
<pre><code>##    output   prediction age sex cp trtbps chol fbs restecg thalachh exng oldpeak
## 1       1  0.772024550  63   1  3    145  233   1       0      150    0     2.3
## 2       1  0.812673171  56   1  1    120  236   0       1      178    0     0.8
## 3       1  0.979920303  48   0  2    130  275   0       1      139    0     0.2
## 4       1  1.031488457  58   0  3    150  283   1       0      162    0     1.0
## 5       1  0.875094483  50   0  2    120  219   0       1      158    0     1.6
## 6       1  0.777014942  51   1  2    110  175   0       1      123    0     0.6
## 7       1  0.683245120  53   1  2    130  197   1       0      152    0     1.2
## 8       1  1.086478400  54   0  2    135  304   1       1      170    0     0.0
## 9       1  0.913072411  65   0  2    155  269   0       1      148    0     0.8
## 10      1  0.904405202  65   0  2    160  360   0       0      151    0     0.8
## 11      1  0.960587721  39   1  2    140  321   0       0      182    0     0.0
## 12      1  0.852234606  52   1  1    120  325   0       1      172    0     0.2
## 13      1  0.884196083  47   1  2    138  257   0       0      156    0     0.0
## 14      1  0.298410916  62   1  2    130  231   0       1      146    0     1.8
## 15      1  1.040876943  44   0  2    108  141   0       1      175    0     0.6
## 16      1  0.652276217  52   1  1    134  201   0       1      158    0     0.8
## 17      1  0.715626911  54   1  1    108  309   0       1      156    0     0.0
## 18      1  0.787208966  35   0  0    138  183   0       1      182    0     1.4
## 19      1  0.644604414  51   1  0    140  261   0       0      186    1     0.0
## 20      1  0.772896816  55   0  1    135  250   0       0      161    0     1.4
## 21      1  0.686272568  59   1  1    140  221   0       1      164    1     0.0
## 22      1  1.002777174  41   1  2    112  250   0       1      179    0     0.0
## 23      1  0.753370763  67   0  2    115  564   0       0      160    0     1.6
## 24      1  0.815112245  48   1  2    124  255   1       1      175    0     0.0
## 25      1  0.487309130  57   1  0    132  207   0       1      168    1     0.0
## 26      1  0.737839414  54   0  1    132  288   1       0      159    1     0.0
## 27      1  0.879613379  50   0  1    120  244   0       1      162    0     1.1
## 28      1  0.822462744  64   0  2    140  313   0       1      133    0     0.2
## 29      1  0.357674638  64   0  0    130  303   0       1      122    0     2.0
## 30      1  1.012611297  34   0  1    118  210   0       1      192    0     0.7
## 31      1  0.686837743  47   1  0    112  204   0       1      143    0     0.1
## 32      1  0.949702376  54   0  2    160  201   0       1      163    0     0.0
## 33      1  0.980000797  41   0  1    126  306   0       1      163    0     0.0
## 34      1  1.075149529  42   0  2    120  209   0       1      173    0     0.0
## 35      1  0.776583684  76   0  2    140  197   0       2      116    0     1.1
## 36      1  1.079115103  60   0  3    150  240   0       1      171    0     0.9
## 37      1  0.503513431  66   1  0    160  228   0       0      138    0     2.3
## 38      1  0.589609553  71   0  0    112  149   0       1      125    0     1.6
## 39      1  0.883681925  66   0  2    146  278   0       0      152    0     0.0
## 40      1  0.864680704  55   0  1    132  342   0       1      166    0     1.2
## 41      1  0.902024804  41   1  1    120  157   0       1      182    0     0.0
## 42      0 -0.046425645  67   1  0    160  286   0       0      108    1     1.5
## 43      0 -0.075746967  67   1  0    120  229   0       0      129    1     2.6
## 44      0  0.251835692  62   0  0    140  268   0       0      160    0     3.6
## 45      0  0.041822816  53   1  0    140  203   1       0      155    1     3.1
## 46      0  0.666843746  56   1  2    130  256   1       0      142    1     0.6
## 47      0  0.353637692  58   1  2    132  224   0       0      173    0     3.2
## 48      0  0.108911112  40   1  0    110  167   0       0      114    1     2.0
## 49      0  0.897912143  64   1  2    140  335   0       1      158    0     0.0
## 50      0 -0.025019680  54   1  0    124  266   0       0      109    1     2.2
## 51      0 -0.091818534  60   1  0    145  282   0       0      142    1     2.8
## 52      0  0.394354494  67   1  0    125  254   1       1      163    0     0.2
## 53      0 -0.079573455  62   1  0    120  267   0       1       99    1     1.8
## 54      0  0.643363973  65   1  0    110  248   0       0      158    0     0.6
## 55      0  0.013268011  60   1  0    125  258   0       0      141    1     2.8
## 56      0 -0.277375566  62   0  0    160  164   0       0      145    0     6.2
## 57      0  0.192481828  59   1  0    110  239   0       0      142    1     1.2
## 58      0 -0.049114885  61   1  0    120  260   0       1      140    1     3.6
## 59      0  0.509461215  62   0  2    130  263   0       1       97    0     1.2
## 60      0  0.087687441  65   1  0    135  254   0       0      127    0     2.8
## 61      0 -0.322953522  55   1  0    140  217   0       1      111    1     5.6
## 62      0 -0.212824839  56   0  0    200  288   1       0      133    1     4.0
## 63      0  0.001777402  70   1  0    145  174   0       1      125    1     2.6
## 64      0  0.269600466  62   1  1    120  281   0       0      103    0     1.4
## 65      0  0.192246131  35   1  0    120  198   0       1      130    1     1.6
## 66      0  0.167333457  55   1  0    160  289   0       0      145    1     0.8
## 67      0  0.336599261  51   1  0    140  299   0       1      173    1     1.6
## 68      0  0.286875144  60   1  0    140  293   0       0      170    0     1.2
## 69      0  0.356299572  77   1  0    125  304   0       0      162    1     0.0
## 70      0  0.523474781  48   1  0    124  274   0       0      166    0     0.5
## 71      0  0.180086080  56   0  0    134  409   0       0      150    1     1.9
## 72      0  0.368189706  66   1  1    160  246   0       1      120    1     0.0
## 73      0  0.622640220  54   1  1    192  283   0       0      195    0     0.0
## 74      0 -0.349006248  51   1  0    140  298   0       1      122    1     4.2
## 75      0  0.202041640  50   1  0    144  200   0       0      126    1     0.9
## 76      0  0.669348872  52   1  0    112  230   0       1      160    0     0.0
## 77      0  0.420691124  63   0  0    108  269   0       1      169    1     1.8
## 78      0  0.329080244  54   1  0    110  206   0       0      108    1     0.0
## 79      0  0.042441877  56   1  0    130  283   1       0      103    1     1.6
## 80      0  0.326423105  67   1  0    120  237   0       1       71    0     1.0
## 81      0  0.263144520  47   1  0    110  275   0       0      118    1     1.0
## 82      0  0.617621792  57   1  1    124  261   0       1      141    0     0.3
## 83      0  0.763368535  58   0  1    136  319   1       0      152    0     0.0
## 84      0 -0.007052885  61   1  0    138  166   0       0      125    1     3.6
## 85      0  0.383549672  42   1  0    136  315   0       1      125    1     1.8
## 86      0  0.111391324  61   1  0    140  207   0       0      138    1     1.9
## 87      0  0.495348385  61   1  0    148  203   0       1      161    0     0.0
## 88      0  0.277783312  58   0  0    170  225   1       0      146    1     2.8
## 89      0  0.276325001  59   1  0    164  176   1       0       90    0     1.0
## 90      0 -0.009045852  68   1  0    144  193   1       1      141    0     3.4
## 91      0  0.875864122  57   0  1    130  236   0       0      174    0     0.0
##    slp caa thall
## 1    0   0     1
## 2    2   0     2
## 3    2   0     2
## 4    2   0     2
## 5    1   0     2
## 6    2   0     2
## 7    0   0     2
## 8    2   0     2
## 9    2   0     2
## 10   2   0     2
## 11   2   0     2
## 12   2   0     2
## 13   2   0     2
## 14   1   3     3
## 15   1   0     2
## 16   2   1     2
## 17   2   0     3
## 18   2   0     2
## 19   2   0     2
## 20   1   0     2
## 21   2   0     2
## 22   2   0     2
## 23   1   0     3
## 24   2   2     2
## 25   2   0     3
## 26   2   1     2
## 27   2   0     2
## 28   2   0     3
## 29   1   2     2
## 30   2   0     2
## 31   2   0     2
## 32   2   1     2
## 33   2   0     2
## 34   1   0     2
## 35   1   0     2
## 36   2   0     2
## 37   2   0     1
## 38   1   0     2
## 39   1   1     2
## 40   2   0     2
## 41   2   0     2
## 42   1   3     2
## 43   1   2     3
## 44   0   2     2
## 45   0   0     3
## 46   1   1     1
## 47   2   2     3
## 48   1   0     3
## 49   2   0     2
## 50   1   1     3
## 51   1   2     3
## 52   1   2     3
## 53   1   2     3
## 54   2   2     1
## 55   1   1     3
## 56   0   3     3
## 57   1   1     3
## 58   1   1     3
## 59   1   1     3
## 60   1   1     3
## 61   0   0     3
## 62   0   2     3
## 63   0   0     3
## 64   1   1     3
## 65   1   0     3
## 66   1   1     3
## 67   2   0     3
## 68   1   2     3
## 69   2   3     2
## 70   1   0     3
## 71   1   2     3
## 72   1   3     1
## 73   2   1     3
## 74   1   3     3
## 75   1   0     3
## 76   2   1     2
## 77   1   2     2
## 78   1   1     2
## 79   0   0     3
## 80   1   0     2
## 81   1   1     2
## 82   2   0     3
## 83   2   2     2
## 84   1   1     2
## 85   1   0     1
## 86   2   1     3
## 87   2   1     3
## 88   1   2     1
## 89   1   2     1
## 90   1   2     3
## 91   1   1     2</code></pre>
<pre class="r"><code>confusion_matrix &lt;- full_results %&gt;% 
  mutate(correct_prediction = ifelse(output == round(prediction,0),&quot;CORRECT&quot;,&quot;INCORRECT&quot;))</code></pre>
<pre class="r"><code>(cf &lt;- confusion_matrix %&gt;% 
  count(correct_prediction))</code></pre>
<pre><code>##   correct_prediction  n
## 1            CORRECT 78
## 2          INCORRECT 13</code></pre>
<p>The lasso regression is correct for 85.71% of the testing observations.</p>
</div>
